name: Build and publish lib

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  release:
    types:
      - published
  workflow_dispatch:
  repository_dispatch:

jobs:
  build-and-publish:
    name: Publish
    runs-on: ubuntu-latest
    timeout-minutes: 10
    concurrency: build-and-publish
    defaults:
      run:
        working-directory: ./lib
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: npm

      - run: npm ci --no-fund --prefer-offline --no-audit

      - name: Cache node modules
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Set version in package.json
        run: npm version --no-git-tag-version "${{ github.ref_name }}"

      - run: npm run build

      - run: npm publish
        if: github.event_name == 'release'
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
